[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"
# Linting + import sorting
select = ["E", "F", "I"]
ignore = ["E501"]  # Let Black handle line length
